# Generated by Django 2.2.5 on 2020-03-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('st_id', models.CharField(max_length=8)),
                ('level', models.IntegerField()),
                ('program', models.CharField(max_length=200)),
            ],
        ),
    ]
