# Generated by Django 2.2.5 on 2020-03-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='type',
            field=models.CharField(choices=[('Bsc', 'Bachelor of Science'), ('Ba', 'Bachelor of Art'), ('Cert', 'Certificate'), ('Dipl', 'Diploma'), ('Hnr', 'Honours'), ('Ms', 'Masters of Science'), ('Ma', 'Masters of Art'), ('PhD', 'Doctor of Philosophy')], default='Bsc', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='level',
            field=models.IntegerField(choices=[(100, 'FR'), (200, 'SO'), (300, 'JR'), (400, 'SR')], default=100),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='program',
            field=models.CharField(choices=[('None', 'Spectator'), ('CS', 'Computer Science'), ('MATH', 'Mathematics'), ('STAT', 'Statistics'), ('IT', 'Information Technology'), ('PHY', 'Physics'), ('CHEM', 'Chemistry')], default='NONE', max_length=200),
        ),
    ]
